fun main() {
    val phillips = TV("Phillips", "P34", 34.0, 5)
    phillips.printInfo()
    println()
    phillips.toTurnOn()
    phillips.toTurnOn()
    println()
    phillips.volumeUp(30)
    println()
    phillips.volumeDown(30)
    println()
    phillips.chooseChannel(4)
    println()
    for (i in 1..5)
        phillips.channelUp()
    println()
    for (i in 1..5)
        phillips.channelDown()
    println()
    phillips.getChannelList()
    println()

    val samsung = TV("Samsung", "U-8588", 55.0, 2)
    samsung.printInfo()
    println()
    samsung.toTurnOn()
    println()
    for (i in 1..5)
        samsung.volumeUp(30)
    println()
    for (i in 1..5)
        samsung.volumeDown(30)
    println()
    samsung.chooseChannel(4)
    println()
    for (i in 1..5)
        samsung.channelUp()
    println()
    for (i in 1..5)
        samsung.channelDown()
    println()
    samsung.getChannelList()
    println()

    val LG = TV("LG", "E-654", 43.0, 20)
    LG.printInfo()
    println()
    LG.toTurnOn()
    println()
    for (i in 1..5)
        LG.volumeUp(30)
    println()
    for (i in 1..5)
        LG.volumeDown(30)
    println()
    LG.chooseChannel(10)
    println()
    for (i in 1..10)
        LG.channelUp()
    println()
    for (i in 1..10)
        LG.channelDown()
    println()
    LG.getChannelList()
    println()
}