fun main() {
    val sber = DebitSberCard(1000.0, 0.009)
    val alfa = DebitAlfaCard(10000.0)
    val vtb = CreditVtbCard(100000.0, 1.0)
    sber.charge()
    sber.pay()
    sber.pay()
    sber.pay()
    sber.pay()
    sber.charge()
    sber.pay()
    sber.pay()
    sber.pay()
    sber.pay()
    sber.charge()
    sber.pay()
    sber.pay()
    sber.pay()

    alfa.charge()
    alfa.pay()
    alfa.pay()
    alfa.pay()
    alfa.pay()
    alfa.pay()
    alfa.charge()
    alfa.pay()
    alfa.pay()
    alfa.pay()
    alfa.pay()
    alfa.pay()
    alfa.pay()

    vtb.charge()
    vtb.pay()
    vtb.pay()
    vtb.pay()
    vtb.pay()
    vtb.pay()
    vtb.charge()
    vtb.pay()
    vtb.pay()
    vtb.pay()
    vtb.pay()
    vtb.pay()
    vtb.pay()
}